List videoAssetPath = [
  {
    'video' : 'assets/video/video7.mp4',
    'username' : '@drashtipatel29',
    'comments' : 200,
    'likes' : 420,
    'share' : '8k',
    'name' : '@drashtipatel29',
  },
  {
    'video' : 'assets/video/video9.mp4',
    'username' : '@gopal.sharma789',
    'comments' : 10,
    'likes' : 350,
    'share' : '2k',
    'name' : '@gopal.sharma789',
  },
  {
    'video' : 'assets/video/video14.mp4',
    'username' : '@niks125',
    'comments' : 500,
    'likes' : 1000,
    'share' : '5.0k',
    'name' : '@niks125',
  },
  {
    'video' : 'assets/video/video5.mp4',
    'username' : '@anushka10',
    'comments' : 100,
    'likes' : 700,
    'share' : '2k',
    'name' : '@anushka10',
  },
  {
    'video' : 'assets/video/video1.mp4',
    'username' : '@sara.alikhan',
    'comments' : 115,
    'likes' : 200,
    'share' : '2.2k',
    'name' : '@sara.alikhan',
  },
  {
    'video' : 'assets/video/video3.mp4',
    'username' : '@rahul36',
    'comments' : 90,
    'likes' : 500,
    'share' : '1k',
    'name' : '@rahul36',
  },
  {
    'video' : 'assets/video/video4.mp4',
    'username' : '@aaliya569',
    'comments' : 50,
    'likes' : 1000,
    'share' : '3.0k',
    'name' : '@aaliya569',
  },
  {
    'video' : 'assets/video/video6.mp4',
    'username' : '@viral00',
    'comments' : 100,
    'likes' : 600,
    'share' : '3.5k',
    'name' : '@viral00',
  },
  {
    'video' : 'assets/video/video8.mp4',
    'username' : '@sweta56',
    'comments' : 25,
    'likes' : 110,
    'share' : '1k',
    'name' : '@sweta56',
  },
  {
    'video' : 'assets/video/video10.mp4',
    'username' : '@sivam.dubey54',
    'comments' : 50,
    'likes' : 220,
    'share' : '3.0k',
    'name' : '@sivam.dubey54',
  },
  {
    'video' : 'assets/video/video11.mp4',
    'username' : '@pratikjain456',
    'comments' : 70,
    'likes' : 610,
    'share' : '5.0k',
    'name' : '@pratikjain456',
  },
  {
    'video' : 'assets/video/video12.mp4',
    'username' : '@krish789',
    'comments' : 90,
    'likes' : 100,
    'share' : '1.0k',
    'name' : '@krish789',
  },
  {
    'video' : 'assets/video/video13.mp4',
    'username' : '@subhampatel',
    'comments' : 200,
    'likes' : 400,
    'share' : '1.0k',
    'name' : '@subhampatel',
  },
];